apiVersion: v1
kind: Pod
metadata:
  name: nonroot-pod
  namespace: demo-star-lord
spec:
  containers:
    - name: app
      image: guardian-demo:secure
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - "ALL"
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
