apiVersion: v1
kind: Pod
metadata:
  name: test-root-pod
  namespace: demo-star-lord
spec:
  containers:
    - name: app
      image: guardian-demo:insecure
      command: ["sleep", "3600"]
      securityContext:
        runAsUser: 0