#requires -Version 7.0
<#
.SYNOPSIS
    Supply Chain Trust Demo - Cleanup Script (PowerShell twin of cleanup.sh).

.DESCRIPTION
    Removes demo-2-specific artifacts and container images generated by
    run-pipeline.{sh,ps1}.

    This does NOT remove the shared 'registry' container or the kind cluster —
    those are part of the shared cluster lifecycle and are torn down by
    scripts/teardown-kind-cluster.{sh,ps1}.

    Safe to run repeatedly: no errors if the artifacts/images are already gone.

.PARAMETER Force
    Reserved for parity/CI use; cleanup runs non-interactively regardless.
#>
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# Resolve paths relative to this script so it can be run from anywhere.
$scriptDir   = $PSScriptRoot
$projectRoot = Split-Path -Parent $scriptDir
$artifactDir = Join-Path $projectRoot 'artifacts'

Write-Host "🧹 Supply Chain Trust Demo - Cleanup" -ForegroundColor Cyan
Write-Host "======================================" -ForegroundColor Cyan
Write-Host "Removing demo-2-specific artifacts and images"
Write-Host ""

# ── Step 1: Remove generated artifacts (idempotent) ─────────────────────────
Write-Host "[1/3] Removing generated artifacts" -ForegroundColor Cyan
if (Test-Path -LiteralPath $artifactDir) {
    foreach ($pattern in @('*.json', '*.txt', '*.spdx')) {
        Get-ChildItem -LiteralPath $artifactDir -Filter $pattern -File -ErrorAction SilentlyContinue |
            Remove-Item -Force -ErrorAction SilentlyContinue
    }
}
$sbom = Join-Path $projectRoot 'attestations/sbom.json'
Remove-Item -LiteralPath $sbom -Force -ErrorAction SilentlyContinue
Write-Host "✅ Artifacts cleaned"

# ── Step 2: Remove in-cluster admission resources (idempotent) ──────────────
Write-Host "[2/3] Removing in-cluster admission resources" -ForegroundColor Cyan
$manifestDir = Join-Path $projectRoot 'manifests'
if (Get-Command kubectl -ErrorAction SilentlyContinue) {
    kubectl delete -f (Join-Path $manifestDir 'deploy-unsigned.yaml') --ignore-not-found 2>$null | Out-Null
    kubectl delete -f (Join-Path $manifestDir 'deploy-signed.yaml') --ignore-not-found 2>$null | Out-Null
    kubectl delete -f (Join-Path $manifestDir 'policy-require-signature.yaml') --ignore-not-found 2>$null | Out-Null
    kubectl delete clusterpolicy verify-supply-chain-signatures --ignore-not-found 2>$null | Out-Null
    kubectl delete -f (Join-Path $manifestDir 'demo-namespace.yaml') --ignore-not-found 2>$null | Out-Null
    kubectl delete namespace demo-gamora --ignore-not-found 2>$null | Out-Null
    kubectl -n kyverno delete secret guardian-cosign-pub --ignore-not-found 2>$null | Out-Null
    Write-Host "✅ Namespace, ClusterPolicy, and cosign public-key secret removed"
} else {
    Write-Host "ℹ️  kubectl not found — skipping in-cluster cleanup (nothing to remove or no cluster)."
}

# ── Step 3: Remove demo images (idempotent) ─────────────────────────────────
Write-Host "[3/3] Removing demo images" -ForegroundColor Cyan
foreach ($reg in @('localhost:5000', '127.0.0.1:5000', 'registry:5000')) {
    foreach ($tag in @('v0.1.0-secure', 'v0.1.0-unsigned')) {
        docker rmi "$reg/guardian-demo-app:$tag" 2>$null | Out-Null
    }
}
docker rmi 'guardian-demo-app:v0.1.0-secure' 2>$null | Out-Null
Write-Host "✅ Demo images removed"

Write-Host ""
Write-Host "✅ Cleanup completed successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Removed resources:"
Write-Host "• Generated SBOMs and scan reports"
Write-Host "• demo-gamora namespace, verify-supply-chain-signatures ClusterPolicy, guardian-cosign-pub secret"
Write-Host "• Demo container images"
Write-Host ""
Write-Host "Note: Cosign keys in ../keys/ are preserved for reuse" -ForegroundColor Yellow
Write-Host "Note: The shared 'registry' container and kind cluster are NOT removed here;" -ForegroundColor Yellow
Write-Host "      tear those down with scripts/teardown-kind-cluster.ps1"
